# Generated by Django 4.1.7 on 2023-05-03 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Woman_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnant_times', models.IntegerField()),
                ('children', models.IntegerField()),
                ('pregnant_date', models.DateTimeField()),
                ('expected_birth', models.DateTimeField()),
                ('pregnancy_status', models.CharField(choices=[('Pregnant', 'P'), ('NotPregnant', 'N')], max_length=64)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=128)),
                ('sector', models.CharField(max_length=128)),
                ('cell', models.CharField(max_length=128)),
                ('village', models.CharField(max_length=128)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
