# Generated by Django 4.1.7 on 2023-05-04 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_woman_info_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Woman_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnant_times', models.IntegerField()),
                ('children', models.IntegerField()),
                ('pregnant_date', models.DateTimeField()),
                ('expected_birth', models.DateTimeField()),
                ('pregnancy_status', models.CharField(choices=[('Pregnant', 'Y'), ('NotPregnant', 'N')], max_length=64)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Woman_info',
        ),
    ]
