# Generated by Django 4.1.7 on 2023-05-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_woman_profile_delete_woman_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman_profile',
            name='pregnancy_status',
            field=models.CharField(choices=[('Pregnant', 'Yes'), ('NotPregnant', 'No')], max_length=64),
        ),
    ]
