# Generated by Django 4.1.7 on 2023-05-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_woman_profile_pregnancy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman_profile',
            name='pregnancy_status',
            field=models.CharField(choices=[('Pregnant', 'yes'), ('Not Pregnant', 'no')], max_length=64),
        ),
    ]
