# Generated by Django 4.1.7 on 2023-05-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_woman_profile_pregnancy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman_profile',
            name='expected_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='woman_profile',
            name='pregnant_date',
            field=models.DateField(),
        ),
    ]
